### ISSUE TITLE
Funding Information

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-ui#12]
Please add the following statement to the main page of the UI: "ICEES+ is a joint creation of RENCI and CoVar with support provided by the National Center for Advancing Translational Sciences, National Institutes of Health [OT3TR002020, OT2TR003430, UL1TR002489] and the Intramural Research Program of the National Institute of Environmental Health Sciences, National Institutes of Health. See Terms and Conditions of Service."

**Comment by maximusunc** [comment]
Added in #19
