### ISSUE TITLE
Replacement Filler Text for Main Page

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-ui#18]
Please replace the filler text on the main page with the following text and hyperlinks:

ICEES provides regulatory-compliant access to clinical data derived from electronic health records, survey data, and genomic data (SNPs) on patients within UNC Health and participants within the Environmental Polymorphisms Registry (EPR) at the National Institute of Environmental Health Sciences. ICEES is currently restricted to UNC Health patients and EPR participants with asthma-like conditions. However, the service was developed as a disease-agnostic framework and approach to overcome the regulatory, cultural, and technical challenges that hinder efforts to openly share clinical data, and new use cases are in development, including those focused on COVID-19, drug-induced liver injury, and primary ciliary dyskinesia.

Additional information on ICEES can be found [here](https://researchsoftwareinstitute.github.io/data-translator/apps/icees).

The ICEES API can be accessed [here](https://icees.renci.org:16339/apidocs/).

We welcome new user engagement! Please post issues, comments, and suggestions on the UI [here](https://github.com/NCATS-Tangerine/icees-ui/issues) and the API [here](https://github.com/NCATS-Tangerine/icees-api/issues).

**Comment by maximusunc** [comment]
Changed in #19
